// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHcqnunQkZJW4ozDSqjv_13C-fadWWLs',
    appId: '1:189026478412:web:0a79bd7de0ec8a658147e9',
    messagingSenderId: '189026478412',
    projectId: 'vans456-98d77',
    authDomain: 'vans456-98d77.firebaseapp.com',
    storageBucket: 'vans456-98d77.firebasestorage.app',
    measurementId: 'G-PS3RPRHLST',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO-fXRE28007AfeFyYV8YksJXQEiFYOxk',
    appId: '1:189026478412:ios:6ffb3f0f04218e718147e9',
    messagingSenderId: '189026478412',
    projectId: 'vans456-98d77',
    storageBucket: 'vans456-98d77.firebasestorage.app',
    iosBundleId: 'com.example.noteIly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO-fXRE28007AfeFyYV8YksJXQEiFYOxk',
    appId: '1:189026478412:ios:6ffb3f0f04218e718147e9',
    messagingSenderId: '189026478412',
    projectId: 'vans456-98d77',
    storageBucket: 'vans456-98d77.firebasestorage.app',
    iosBundleId: 'com.example.noteIly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQHcqnunQkZJW4ozDSqjv_13C-fadWWLs',
    appId: '1:189026478412:web:834425d85c028f3c8147e9',
    messagingSenderId: '189026478412',
    projectId: 'vans456-98d77',
    authDomain: 'vans456-98d77.firebaseapp.com',
    storageBucket: 'vans456-98d77.firebasestorage.app',
    measurementId: 'G-HBEY48RZX3',
  );

}